#include <unity.h>
#include <Arduino.h>
#include <DeviceFramework.h>
#include <Configuration/DeviceFrameworkConfig.h>

// Include test configuration if available (generated by run-tests.sh)
#ifdef __has_include
    #if __has_include("test_config.h")
        #include "test_config.h"
    #endif
#endif

// Test DeviceFramework configuration methods (second test - parameter setting and verification)
void test_device_framework_configuration() {
    Serial.println("[TEST]   Testing DeviceFramework configuration methods...");

    // Store original values to restore later (copy to local stack variables)
    String originalDeviceName = DeviceFramework::getDeviceName() ? String(DeviceFramework::getDeviceName()) : String("");
    String originalMqttServer = DeviceFramework::getMqttServer() ? String(DeviceFramework::getMqttServer()) : String("");
    uint16_t originalMqttPort = DeviceFramework::getMqttPort();
    String originalMqttUser = DeviceFramework::getMqttUser() ? String(DeviceFramework::getMqttUser()) : String("");
    String originalMqttPassword = DeviceFramework::getMqttPass() ? String(DeviceFramework::getMqttPass()) : String("");
    String originalDevicePassword = DeviceFramework::getDevicePassword();
    const uint32_t originalMDNSMinLargestBlock = getConfigMDNSMinLargestBlock();
    const uint32_t originalMDNSUpdateInterval = getConfigMDNSUpdateInterval();

    // Set test parameters
    DeviceFramework::setDeviceName("TestDevice");
    DeviceFramework::setMqttServer("test.mqtt.server");
    DeviceFramework::setMqttPort(8883);
    DeviceFramework::setMqttUser("testuser");
    DeviceFramework::setMqttPass("testpass");

    // Test that parameters were set correctly
    const char* deviceName = DeviceFramework::getDeviceName();
    TEST_ASSERT_NOT_NULL_MESSAGE(deviceName, "Device name should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("TestDevice", deviceName,
        "Device name should be set to 'TestDevice'");

    const char* mqttServer = DeviceFramework::getMqttServer();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttServer, "MQTT server should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("test.mqtt.server", mqttServer,
        "MQTT server should be set to 'test.mqtt.server'");

    uint16_t mqttPort = DeviceFramework::getMqttPort();
    TEST_ASSERT_EQUAL_MESSAGE(8883, mqttPort,
        "MQTT port should be set to 8883");

    const char* mqttUser = DeviceFramework::getMqttUser();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttUser, "MQTT user should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testuser", mqttUser,
        "MQTT user should be set to 'testuser'");

    const char* mqttPass = DeviceFramework::getMqttPass();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttPass, "MQTT password should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testpass", mqttPass,
        "MQTT password should be set to 'testpass'");

    // A profiled fresh V4 record receives its initial seed; ordinary builds
    // intentionally start open so both modes remain covered.
    const char* devicePassword = DeviceFramework::getDevicePassword();
    TEST_ASSERT_NOT_NULL_MESSAGE(devicePassword, "Device password should not be NULL");
#if defined(DEVICEFRAMEWORK_HAS_LOCAL_PROFILE) && DEVICEFRAMEWORK_HAS_LOCAL_PROFILE
    TEST_ASSERT_EQUAL_STRING_MESSAGE("profile-fixture-password", devicePassword,
        "Profiled test firmware should seed its shared device password");
#else
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", devicePassword,
        "Device password should be empty for testing");
#endif

    TEST_ASSERT_FALSE_MESSAGE(DeviceFramework::setDevicePassword("short"),
        "Short device passwords must be rejected before writing storage");
    TEST_ASSERT_TRUE_MESSAGE(DeviceFramework::setDevicePassword("testadmin"),
        "A valid device password should persist transactionally");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testadmin", DeviceFramework::getDevicePassword(),
        "The public API should expose the activated password");
    TEST_ASSERT_TRUE_MESSAGE(DeviceFramework::setDevicePassword(""),
        "An explicit empty password should remain supported");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", DeviceFramework::getDevicePassword(),
        "An explicit empty password should disable local authentication");


    setConfigMDNSMinLargestBlock(3072);
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(3072, getConfigMDNSMinLargestBlock(),
        "mDNS contiguous-heap guard should be configurable");
    setConfigMDNSMinLargestBlock(originalMDNSMinLargestBlock);
    setConfigMDNSUpdateInterval(50);
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(50, getConfigMDNSUpdateInterval(),
        "mDNS parser attempt interval should be configurable");
    setConfigMDNSUpdateInterval(originalMDNSUpdateInterval);

    // Restore original values
    DeviceFramework::setDeviceName(originalDeviceName.c_str());
    if (originalMqttServer.length() > 0) {
        DeviceFramework::setMqttServer(originalMqttServer.c_str());
    }
    DeviceFramework::setMqttPort(originalMqttPort);
    if (originalMqttUser.length() > 0) {
        DeviceFramework::setMqttUser(originalMqttUser.c_str());
    }
    if (originalMqttPassword.length() > 0) {
        DeviceFramework::setMqttPass(originalMqttPassword.c_str());
    }
    TEST_ASSERT_TRUE_MESSAGE(DeviceFramework::setDevicePassword(originalDevicePassword.c_str()),
        "The original device password should restore transactionally");

    // Verify that original values were restored correctly
    const char* restoredDeviceName = DeviceFramework::getDeviceName();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredDeviceName, "Restored device name should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalDeviceName.c_str(), restoredDeviceName,
        "Device name should be restored to original value");

    const char* restoredMqttServer = DeviceFramework::getMqttServer();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttServer, "Restored MQTT server should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttServer.c_str(), restoredMqttServer,
        "MQTT server should be restored to original value");

    uint16_t restoredMqttPort = DeviceFramework::getMqttPort();
    TEST_ASSERT_EQUAL_MESSAGE(originalMqttPort, restoredMqttPort,
        "MQTT port should be restored to original value");

    const char* restoredMqttUser = DeviceFramework::getMqttUser();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttUser, "Restored MQTT user should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttUser.c_str(), restoredMqttUser,
        "MQTT user should be restored to original value");

    const char* restoredMqttPass = DeviceFramework::getMqttPass();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttPass, "Restored MQTT password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttPassword.c_str(), restoredMqttPass,
        "MQTT password should be restored to original value");
}
