#include <unity.h>
#include <Arduino.h>
#include <DeviceFramework.h>
#include <Configuration/DeviceFrameworkConfig.h>

// Include test configuration if available (generated by run-tests.sh)
#ifdef __has_include
    #if __has_include("test_config.h")
        #include "test_config.h"
    #endif
#endif

// Test DeviceFramework configuration methods (second test - parameter setting and verification)
void test_device_framework_configuration() {
    Serial.println("[TEST]   Testing DeviceFramework configuration methods...");

    // Store original values to restore later (copy to local stack variables)
    String originalDeviceName = DeviceFramework::getDeviceName() ? String(DeviceFramework::getDeviceName()) : String("");
    String originalMqttServer = DeviceFramework::getMqttServer() ? String(DeviceFramework::getMqttServer()) : String("");
    uint16_t originalMqttPort = DeviceFramework::getMqttPort();
    String originalMqttUser = DeviceFramework::getMqttUser() ? String(DeviceFramework::getMqttUser()) : String("");
    String originalMqttPassword = DeviceFramework::getMqttPass() ? String(DeviceFramework::getMqttPass()) : String("");
    String originalConfigVersion = getConfigVersion() ? String(getConfigVersion()) : String("");
    String originalAdminPassword = getConfigAdminPassword() ? String(getConfigAdminPassword()) : String("");

    // Set test parameters
    DeviceFramework::setDeviceName("TestDevice");
    DeviceFramework::setMqttServer("test.mqtt.server");
    DeviceFramework::setMqttPort(8883);
    DeviceFramework::setMqttUser("testuser");
    DeviceFramework::setMqttPass("testpass");

    // Test that parameters were set correctly
    const char* deviceName = DeviceFramework::getDeviceName();
    TEST_ASSERT_NOT_NULL_MESSAGE(deviceName, "Device name should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("TestDevice", deviceName,
        "Device name should be set to 'TestDevice'");

    const char* mqttServer = DeviceFramework::getMqttServer();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttServer, "MQTT server should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("test.mqtt.server", mqttServer,
        "MQTT server should be set to 'test.mqtt.server'");

    uint16_t mqttPort = DeviceFramework::getMqttPort();
    TEST_ASSERT_EQUAL_MESSAGE(8883, mqttPort,
        "MQTT port should be set to 8883");

    const char* mqttUser = DeviceFramework::getMqttUser();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttUser, "MQTT user should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testuser", mqttUser,
        "MQTT user should be set to 'testuser'");

    const char* mqttPass = DeviceFramework::getMqttPass();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttPass, "MQTT password should not be NULL after setting");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testpass", mqttPass,
        "MQTT password should be set to 'testpass'");

    // Test admin password - should return empty value (set for testing)
    const char* adminPassword = getConfigAdminPassword();
    TEST_ASSERT_NOT_NULL_MESSAGE(adminPassword, "Admin password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", adminPassword,
        "Admin password should be empty for testing");

    // Test setting admin password
    setConfigAdminPassword("testadmin");
    const char* newAdminPassword = getConfigAdminPassword();
    TEST_ASSERT_NOT_NULL_MESSAGE(newAdminPassword, "New admin password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("testadmin", newAdminPassword,
        "Admin password should be set to 'testadmin'");

    // Test setting empty admin password (should be allowed)
    setConfigAdminPassword("");
    const char* emptyAdminPassword = getConfigAdminPassword();
    TEST_ASSERT_NOT_NULL_MESSAGE(emptyAdminPassword, "Empty admin password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", emptyAdminPassword,
        "Admin password should be empty string");

    // Test setting NULL admin password (should also result in empty string)
    setConfigAdminPassword(nullptr);
    const char* nullAdminPassword = getConfigAdminPassword();
    TEST_ASSERT_NOT_NULL_MESSAGE(nullAdminPassword, "NULL admin password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", nullAdminPassword,
        "Admin password should be empty string after setting NULL");

    // Test config version - should return default value
    const char* configVersion = getConfigVersion();
    TEST_ASSERT_NOT_NULL_MESSAGE(configVersion, "Config version should not be NULL");
    TEST_ASSERT_TRUE_MESSAGE(strlen(configVersion) > 0,
        "Config version should not be empty");

    // Test setting empty version (should be allowed)
    setConfigVersion("");
    const char* emptyVersion = getConfigVersion();
    TEST_ASSERT_NOT_NULL_MESSAGE(emptyVersion, "Empty version should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE("", emptyVersion,
        "Version should be empty string");

    // Restore original values
    DeviceFramework::setDeviceName(originalDeviceName.c_str());
    if (originalMqttServer.length() > 0) {
        DeviceFramework::setMqttServer(originalMqttServer.c_str());
    }
    DeviceFramework::setMqttPort(originalMqttPort);
    if (originalMqttUser.length() > 0) {
        DeviceFramework::setMqttUser(originalMqttUser.c_str());
    }
    if (originalMqttPassword.length() > 0) {
        DeviceFramework::setMqttPass(originalMqttPassword.c_str());
    }
    if (originalConfigVersion.length() > 0) {
        setConfigVersion(originalConfigVersion.c_str());
    }
    setConfigAdminPassword(originalAdminPassword.c_str());

    // Verify that original values were restored correctly
    const char* restoredDeviceName = DeviceFramework::getDeviceName();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredDeviceName, "Restored device name should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalDeviceName.c_str(), restoredDeviceName,
        "Device name should be restored to original value");

    const char* restoredMqttServer = DeviceFramework::getMqttServer();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttServer, "Restored MQTT server should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttServer.c_str(), restoredMqttServer,
        "MQTT server should be restored to original value");

    uint16_t restoredMqttPort = DeviceFramework::getMqttPort();
    TEST_ASSERT_EQUAL_MESSAGE(originalMqttPort, restoredMqttPort,
        "MQTT port should be restored to original value");

    const char* restoredMqttUser = DeviceFramework::getMqttUser();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttUser, "Restored MQTT user should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttUser.c_str(), restoredMqttUser,
        "MQTT user should be restored to original value");

    const char* restoredMqttPass = DeviceFramework::getMqttPass();
    TEST_ASSERT_NOT_NULL_MESSAGE(restoredMqttPass, "Restored MQTT password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(originalMqttPassword.c_str(), restoredMqttPass,
        "MQTT password should be restored to original value");
}
