#include <unity.h>
#include <Arduino.h>
#include <DeviceFramework.h>
#include <DeviceFrameworkPlatform.h>  // Platform abstraction

// Include test configuration if available (generated by run-tests.sh)
#ifdef __has_include
    #if __has_include("test_config.h")
        #include "test_config.h"
    #endif
#endif

// Test basic DeviceFramework methods (first test - initial state)
void test_device_framework_basic_methods() {
    Serial.println("[TEST]   Testing basic DeviceFramework methods...");

    // Test device name - should return default value
    const char* deviceName = DeviceFramework::getDeviceName();
    TEST_ASSERT_NOT_NULL_MESSAGE(deviceName, "Device name should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(DF_DEFAULT_DEVICE_NAME, deviceName,
        "Device name should be set to 'esp8266-controller'");

    // Test MQTT server - should return test value in TESTING_MODE
    const char* mqttServer = DeviceFramework::getMqttServer();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttServer, "MQTT server should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(TEST_MQTT_SERVER, mqttServer,
        "MQTT server should be set to test server value");

    // Test MQTT port - should return test value (1883)
    uint16_t mqttPort = DeviceFramework::getMqttPort();
    TEST_ASSERT_EQUAL_MESSAGE(1883, mqttPort,
        "MQTT port should be set to 1883");

    // Test MQTT user - should return test value
    const char* mqttUser = DeviceFramework::getMqttUser();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttUser, "MQTT user should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(TEST_MQTT_USER, mqttUser,
        "MQTT user should be set to test user value");

    // Test MQTT password - should return test value
    const char* mqttPassword = DeviceFramework::getMqttPass();
    TEST_ASSERT_NOT_NULL_MESSAGE(mqttPassword, "MQTT password should not be NULL");
    TEST_ASSERT_EQUAL_STRING_MESSAGE(TEST_MQTT_PASSWORD, mqttPassword,
        "MQTT password should be set to test password value");
}
