#include <unity.h>
#include <Arduino.h>
#include <DeviceFramework.h>
#include <Configuration/DeviceFrameworkConfig.h>
#include <WiFiClient.h>
#include <DeviceFrameworkPlatform.h>  // Platform abstraction (includes HTTP client headers)
#include <Storage/DeviceFrameworkStorage.h>
#include <ArduinoHA.h>
#include <Utils/HostnameUtils.h>
#include <Utils/CRC32Utils.h>
#include <Utils/TimeUtils.h>
#include "test_main.h"
#include "utils/test_utils.h"
#include "utils/CachedEndpointTester.h"

// Include test configuration if available (generated by run-tests.sh)
#ifdef __has_include
    #if __has_include("test_config.h")
        #include "test_config.h"
    #endif
#endif

// Test case array - organized by state dependencies
// Group 1: Stateless Utilities (no dependencies)
// Group 2: Initial State Verification (after setup)
// Group 3: Configuration & Storage (independent, can modify state)
// Group 4: Network-Dependent (requires WiFi/MQTT)
// Group 5: ParameterRegistry Integration (modifies parameters)
// Group 6: Web Interface (requires web server)
TestCase tests[] = {
    // Group 1: Stateless Utilities
    TEST_ENTRY(test_hostname_utils),
    TEST_ENTRY(test_crc32_utils),
    TEST_ENTRY(test_time_utils),

    // Group 2: Initial State Verification
    TEST_ENTRY(test_device_framework_basic_methods),
    TEST_ENTRY(test_device_framework_setup_verification),
    TEST_ENTRY(test_eeprom_storage_methods),

    // Group 3: Configuration & Storage
    TEST_ENTRY(test_device_framework_configuration),
    TEST_ENTRY(test_storage_save_load),

    // Group 4: Network-Dependent
    TEST_ENTRY(test_wifi_manager_state),
    TEST_ENTRY(test_device_framework_mqtt_settings),
    TEST_ENTRY(test_mqtt_command_handlers),

    // Group 5: ParameterRegistry Integration
    TEST_ENTRY(test_parameter_registry_integration),
    TEST_ENTRY(test_parameter_registry_ha_origin_updates_shadow_state),

    // Group 6: Web Interface
    TEST_ENTRY(test_web_interface_methods),
    TEST_ENTRY(test_web_interface_http_requests),
};

const size_t TEST_COUNT = sizeof(tests) / sizeof(TestCase);

// Test state variables
size_t next_index = 0;
bool begun = false;
bool frameworkSetup = false;
bool wifiConnected = false;
bool mqttConnected = false;

// Dummy test device entities (simulating typical consuming sketch)
HASensorNumber testSensor("test_sensor", HASensorNumber::PrecisionP1);
HASwitch testSwitch("test_switch");

// Test setup and teardown
void setUp(void) {
    // No per-test setup needed - DeviceFramework is set up once in main setup()
#ifdef ENABLE_MEMORY_LOGGING
    if (next_index < TEST_COUNT) {
        Serial.print("\n[TEST] [MEMORY BEFORE] ");
        Serial.print(tests[next_index].name);
        Serial.print(" - ");
        logTestMemory(tests[next_index].name, "BEFORE");
    }
#endif
}

void tearDown(void) {
    // No per-test teardown needed
#ifdef ENABLE_MEMORY_LOGGING
    if (next_index > 0) {
        Serial.print("\n[TEST] [MEMORY AFTER] ");
        Serial.print(tests[next_index - 1].name);
        Serial.print(" - ");
        logTestMemory(tests[next_index - 1].name, "AFTER");
    }
#endif
}

#ifdef DF_PLATFORM_ESP32
#include <esp_system.h>
#include <soc/soc.h>
#include <soc/rtc_cntl_reg.h>
#include <rom/rtc.h>
#endif

// ESP32 Panic Handler - prints exception info
#ifdef DF_PLATFORM_ESP32
void printExceptionInfo() {
    delay(100);
    Serial.println("\n=== EXCEPTION OCCURRED ===");
    Serial.print("Reset reason: ");
    esp_reset_reason_t reason = esp_reset_reason();
    switch(reason) {
        case ESP_RST_POWERON: Serial.println("Power-on reset"); break;
        case ESP_RST_EXT: Serial.println("External reset"); break;
        case ESP_RST_SW: Serial.println("Software reset"); break;
        case ESP_RST_PANIC: Serial.println("Exception/panic"); break;
        case ESP_RST_INT_WDT: Serial.println("Interrupt watchdog reset"); break;
        case ESP_RST_TASK_WDT: Serial.println("Task watchdog reset"); break;
        case ESP_RST_WDT: Serial.println("Other watchdog reset"); break;
        case ESP_RST_DEEPSLEEP: Serial.println("Deep sleep reset"); break;
        case ESP_RST_BROWNOUT: Serial.println("Brownout reset"); break;
        case ESP_RST_SDIO: Serial.println("SDIO reset"); break;
        default: Serial.println("Unknown"); break;
    }
    Serial.println("==========================\n");
}
#endif

// Arduino setup and loop functions (required by framework)
void setup() {
    #ifdef DF_PLATFORM_ESP32
        // Disable brownout detector to prevent resets during flash operations
        WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);
        // Print exception info if this was a crash restart
        if (esp_reset_reason() == ESP_RST_PANIC || esp_reset_reason() == ESP_RST_TASK_WDT) {
            Serial.begin(115200);
            delay(100);
            printExceptionInfo();
        }
    #endif

    Serial.begin(115200);
    delay(2000); // Give time for serial to initialize
    markSerialAsInitialized(); // Tell framework Serial is already initialized

    Serial.println("\n[TEST] =============================================");
    Serial.println("[TEST] === DeviceFramework Test Setup ===");
    Serial.println("[TEST] Starting DeviceFramework tests...");
    Serial.println("[TEST] =============================================");

    // Clear EEPROM to start with a clean state for testing
    Serial.println("[TEST]   Clearing EEPROM for clean test state...");
    uint16_t eepromSize = getConfigEEPROMSize();
    EEPROM.begin(eepromSize);
    for (size_t i = 0; i < eepromSize; i++) {
        EEPROM.write(i, 0xFF);
    }
    EEPROM.commit();
    #ifdef DF_PLATFORM_ESP8266
        EEPROM.end();
    #endif
    #ifdef DF_PLATFORM_ESP32
        delay(100);
    #endif
    Serial.println("[TEST]   EEPROM cleared");

    // Simulate a real sketch setup - set admin password and register custom parameter
    Serial.println("[TEST]   Configuring test parameters...");

    Serial.println("[TEST]     Setting admin password...");
    setConfigAdminPassword("");


    Serial.println("[TEST]     Calling DeviceFramework::beforeSetup()...");
    DeviceFramework::beforeSetup([]() {
        auto& paramRegistry = DeviceFrameworkParameters::getRegistry();
        DeviceFrameworkParameterMetadata testParamMeta;
        testParamMeta.id = "testdevicename";
        testParamMeta.label = "Test Device Name";
        testParamMeta.sources = SOURCE_WIFI_MANAGER;
        testParamMeta.defaultValue = "test-device";
        testParamMeta.maxLength = 20;
        testParamMeta.order = 5;  // After core parameters (0-4)
        paramRegistry.registerParameter(testParamMeta);
        Serial.println("[TEST]     Custom parameter registered: testdevicename");

        DeviceFrameworkParameterMetadata haSwitchMeta;
        haSwitchMeta.id = "testhaswitch";
        haSwitchMeta.label = "Test HA Switch";
        haSwitchMeta.sources = SOURCE_HOME_ASSISTANT;
        haSwitchMeta.defaultValue = "false";
        haSwitchMeta.maxLength = 5;
        haSwitchMeta.order = 6;
        haSwitchMeta.haDeviceType = HAConfigDeviceType::SWITCH;
        paramRegistry.registerParameter(haSwitchMeta);
        Serial.println("[TEST]     Custom HA parameter registered: testhaswitch");
    });

    // In testing mode, set up WiFi credentials and persist them
    Serial.println("[TEST]   Setting up WiFi credentials...");
    #ifdef DF_PLATFORM_ESP8266
        WiFi.persistent(true);  // ESP8266 only - ESP32 doesn't support this
    #endif
    WiFi.begin(TEST_WIFI_SSID, TEST_WIFI_PASSWORD);

    // Setup DeviceFramework (now with proper sketch-like configuration)
    Serial.println("[TEST]   Setting up DeviceFramework...");
    DeviceFramework::setup();
    frameworkSetup = true;
    Serial.println("[TEST]   DeviceFramework setup completed");

    // Set test parameters after DeviceFramework setup (to override any defaults loaded from EEPROM)
    Serial.println("[TEST]   Setting test parameters...");

    Serial.print("[TEST]     Setting device name: ");
    Serial.println(DF_DEFAULT_DEVICE_NAME);
    DeviceFramework::setDeviceName(DF_DEFAULT_DEVICE_NAME);

    Serial.print("[TEST]     Setting MQTT server: ");
    Serial.println(TEST_MQTT_SERVER);
    DeviceFramework::setMqttServer(TEST_MQTT_SERVER);

    Serial.print("[TEST]     Setting MQTT port: ");
    Serial.println(1883);
    DeviceFramework::setMqttPort(1883);

    Serial.print("[TEST]     Setting MQTT user: ");
    Serial.println(TEST_MQTT_USER);
    DeviceFramework::setMqttUser(TEST_MQTT_USER);

    Serial.print("[TEST]     Setting MQTT password: ");
    Serial.println("[HIDDEN]");
    DeviceFramework::setMqttPass(TEST_MQTT_PASSWORD);

    // Save parameters to EEPROM so they persist
    Serial.println("[TEST]     Saving parameters to EEPROM...");
    DeviceFramework::saveParameters();

    // Add default MQTT command handlers (typical consuming sketch pattern)
    DeviceFramework::addMQTTResetCommand();
    DeviceFramework::addMQTTRestartCommand();

    // Add custom MQTT command handlers for testing
    DeviceFramework::registerSharedCommandHandler("test_command", [](const uint8_t* payload, const uint16_t length) {
        Serial.println("Test shared command received!");
    });

    DeviceFramework::registerDeviceCommandHandler(&testSensor, "test_command", [](const uint8_t* payload, const uint16_t length) {
        Serial.println("Test device command received!");
    });

    // Configure dummy test entities (simulating typical consuming sketch)
    testSensor.setName("Test Sensor");
    testSensor.setUnitOfMeasurement("units");
    testSensor.setIcon("mdi:gauge");

    testSwitch.setName("Test Switch");
    testSwitch.setIcon("mdi:toggle-switch");

    // Add dummy device types to MQTT (typical consuming sketch pattern)
    auto& haMqtt = DeviceFramework::getHAMqtt();
    haMqtt.addDeviceType(&testSensor);
    haMqtt.addDeviceType(&testSwitch);

    Serial.println("[TEST]   Test framework configured with typical consuming sketch patterns");

    UNITY_BEGIN(); // Start Unity test framework
    begun = true; // Start tests immediately
}

void loop() {
    // Run DeviceFramework loop to handle WiFi and MQTT connections non-blocking
    if (frameworkSetup) {
        DeviceFramework::loop();
    }

    // Check WiFi and MQTT connection status and wait before starting tests
    if (begun && (!wifiConnected || !mqttConnected)) {
        bool wifiConnectedNow = WiFi.isConnected();
        bool mqttConnectedNow = DeviceFrameworkMQTT::isConnected();
        bool inConfigMode = DeviceFramework::isInConfigMode();

        // Update WiFi connection status
        if (wifiConnectedNow && !wifiConnected) {
            wifiConnected = true;
            Serial.println("\n[TEST] --- WiFi Connected ---");
            Serial.print("[TEST] IP: ");
            Serial.println(WiFi.localIP());
            Serial.print("[TEST] SSID: ");
            Serial.println(WiFi.SSID());
        }

        // Update MQTT connection status
        if (mqttConnectedNow && !mqttConnected) {
            mqttConnected = true;
            Serial.println("[TEST] --- MQTT Connected ---");
        }

        // Check if we're ready to start tests
        if (wifiConnected && mqttConnected) {
            Serial.println("[TEST] --- All connections ready - Starting tests ---\n");
        } else if (inConfigMode && wifiConnected) {
            // WiFi connected but MQTT failed, but config mode is active - start tests anyway
            mqttConnected = true; // Mark as "ready" to start tests
            Serial.println("[TEST] --- Config mode active - Starting tests ---\n");
        } else {
            // Print status every 5 seconds
            static unsigned long lastStatusPrint = 0;
            if (millis() - lastStatusPrint > 5000) {
                Serial.print("[TEST] Waiting for connections... WiFi: ");
                Serial.print(wifiConnectedNow ? "YES" : "NO");
                Serial.print(", MQTT: ");
                Serial.print(mqttConnectedNow ? "YES" : "NO");
                Serial.print(", Config mode: ");
                Serial.println(inConfigMode ? "YES" : "NO");
                lastStatusPrint = millis();
            }
            return; // Don't start tests yet
        }
    }

    // Run one test and return immediately
    if (begun && wifiConnected && mqttConnected && next_index < TEST_COUNT) {
        TestCase& t = tests[next_index];
        Serial.print("\n[TEST] ==== Running test: ");
        Serial.print(t.name);
        Serial.println(" ====");
        UnityDefaultTestRun(t.fn, t.name, t.line);
        next_index++;
        return; // yield quickly
    }

    // All tests completed
    if (begun && wifiConnected && mqttConnected && next_index >= TEST_COUNT) {
        Serial.println("\n[TEST] =============================================");
        Serial.println("[TEST] === All tests completed ===");
        Serial.println("[TEST] =============================================");
        UNITY_END(); // prints Unity summary
        begun = false; // avoid repeating
    }
}
