#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_asset="$root/assets/deviceframework-mark.svg"
output="${1:-$root/src/WebInterface/templates/WebInterfaceLogo.h}"

if [[ ! -f "$source_asset" ]]; then
    echo "Missing source asset: $source_asset" >&2
    exit 1
fi

encoded="$(base64 --wrap=0 "$source_asset")"
{
    printf '%s\n' '#ifndef WEBINTERFACE_LOGO_H'
    printf '%s\n\n' '#define WEBINTERFACE_LOGO_H'
    printf '%s\n\n' '#include <Arduino.h>'
    printf '%s\n' '// Generated by tools/generate-web-assets.sh from assets/deviceframework-mark.svg.'
    printf '%s' 'const char PROGMEM logo_base64[] = "'
    printf '%s' "$encoded"
    printf '%s\n\n' '";'
    printf '%s\n' '#endif  // WEBINTERFACE_LOGO_H'
} > "$output"

printf 'Generated %s from %s\n' "$output" "$source_asset"
